### ISSUE TITLE
bug: ComboBox menu stealing focus

### ISSUE THREAD

**Issue by FredrikMWold** [equinor/amplify-component-lib#735]
If the user hovers any of the options in the dropdown menu then every time the user types something in the input field after the dropdown menu grabs focus from the input on every key press.

Steps:
- Open dropdown
- Hover over an option
- Click input field and try to type more than one character

![focus grab](https://github.com/user-attachments/assets/d5e7c054-150a-4536-b81a-55463f60b5e1)

**Comment by aslakihle** [comment]
Hey, sorry for late response. 

I have added this to our backlog, and take it up in the next planning.
