### ISSUE TITLE
bug: ComboBox with onAddItem

### ISSUE THREAD

**Issue by FredrikMWold** [equinor/amplify-component-lib#758]
When using the `ComboBox` with the `onAddItem` prop im no longer able to select any items.

![Peek 2024-09-25 11-25](https://github.com/user-attachments/assets/7424cde2-5bb8-4d7a-9fa0-6932b4a4ef64)

**Comment by mariush2** [comment]
Not sure if you're just getting this issue in the storybook, I see the same bug when in the 'docs' storybook page for the ComboBox, but it works in the single story for onAdd: https://client-storybook-amplify-components-production.radix.equinor.com/?path=/story/molecules-select-combobox--combo-box-with-add

**Comment by FredrikMWold** [comment]
Ah, yes did not see that the example has a hardcoded empty value array.
