### ISSUE TITLE
ComboBox submitting form

### ISSUE THREAD

**Issue by FredrikMWold** [equinor/amplify-component-lib#830]
When using the the `ComboBox` inside a form.
The form get submitted when cliking on an item with the mouse or using the keyboard

![Image](https://github.com/user-attachments/assets/18e66b31-a9ba-423f-bd36-ca050206df62)

**Comment by FredrikMWold** [comment]
This is an issue upstream in EDS. I have made a pull-request to fix it.
The problem is missing `type="buttom"` and `closeMenuOnClick`.

**Comment by mariush2** [comment]
Hey! Thanks for the feedback, I can get this fixed today I think, should be a quick fix

**Comment by FredrikMWold** [comment]
EDS also merged my PR to fix it upstream
