### ISSUE TITLE
bug: RichTextEdtior causes application to crash

### ISSUE THREAD

**Issue by FredrikMWold** [equinor/amplify-component-lib#911]
When using the `RichTextEditor` component the whole crashes with this error.

![Image](https://github.com/user-attachments/assets/de5b044e-3363-4824-b50e-0501a2cb5c06)

**Comment by mariush2** [comment]
This is happening because you're missing a react query queryclient provider, are you not using react query?

**Comment by FredrikMWold** [comment]
No, I do not use react query.

**Comment by FredrikMWold** [comment]
No, i don't use the image upload functionality, but I think that i should be able to without using react-query.
Dependencies like that should not be internal to the component, but should be callback handlers that could use any fetch implementation, react-query mutation or an RTK-mutation

**Comment by mariush2** [comment]
Ok that's fine, but we all use react query in the amplify applications, so we use it everywhere to do API calls.

To remove it you can do this:

```tsx

<RichTextEditor removeFeatures={[RichTextEditorFeatures.IMAGES]} ... />
```
